# Generated by Django 3.1.7 on 2021-07-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ulimiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField()),
                ('ulimit', models.IntegerField()),
            ],
        ),
    ]
